### ISSUE TITLE
EPIC: Install Anywhere

### ISSUE THREAD

**Issue by twangboy** [saltstack/community#132]
- [ ] SALT: Configure for dynamic location (#134)
- [ ] SALT: Get locations from registry (#135)
- [ ] SALT: Set permissions (#136)
- [ ] NSIS: Update Installer (#137)
- [ ] NSIS: User Selectable location (#138)
- [ ] How to handle the MSI logic

https://github.com/saltstack/salt-enhancement-proposals/blob/master/accepted/0031-windows-install-anywhere.md

https://github.com/saltstack/salt/issues/42801

Salt: Program Files
System Config: ProgramData
User Config: AppData

This would allow for running a minion in the System context and the User context
