### ISSUE TITLE
EPIC: Winrepo

### ISSUE THREAD

**Issue by twangboy** [saltstack/community#139]
- [x] Fix 403 redirects in tests
- [x] Fix other issues with URLs in the tests (https://github.com/saltstack/salt-winrepo-ng/pull/1833/checks)
- [x] Fix scheduled Jobs
